services:
    php:
        build:
            context: ..
            dockerfile: docker-dev/Dockerfile
        container_name: lingo_step_php
        working_dir: /var/www
        volumes:
            - ../:/var/www
        depends_on:
            - db
        environment:
            SYMFONY_HOME: /tmp/.symfony5

    caddy:
        build:
            context: ..
            dockerfile: docker-dev/Dockerfile.caddy
        container_name: lingo_step_caddy
        ports:
            - "8443:8443"
        volumes:
            - ../:/var/www
            - caddy_data:/data
            - caddy_config:/config
        depends_on:
            - php

    db:
        image: mariadb:latest
        container_name: lingo_step_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lingo_step_db
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3308:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lingo_step_phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        depends_on:
            - db
    node:
        image: node:22
        container_name: lingo_step_node
        working_dir: /var/www
        volumes:
            - ../:/var/www
        command: tail -f /dev/null

volumes:
    db_data:
    caddy_data:
    caddy_config:
